# Generated by Django 4.0.4 on 2022-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detailsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(default='address', max_length=90)),
                ('services', models.CharField(default='services', max_length=90)),
            ],
        ),
    ]
